# Generated by Django 4.0.6 on 2022-07-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfileupload',
            name='file_upload',
            field=models.FileField(upload_to='images'),
        ),
    ]
