# Generated by Django 4.0.6 on 2022-07-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_messageattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'ordering': ['created_date']},
        ),
    ]
