# Generated by Django 4.0.6 on 2022-07-11 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
