# Generated by Django 4.0.6 on 2022-07-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_is_online'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_date']},
        ),
    ]
